### ISSUE TITLE
IPFS version is broken

### ISSUE THREAD

**Issue by xuhcc** [balancer-labs/snapshot#101]
It seems that http://snapshot.page has DNSLink enabled, but linked [IPFS site](
https://ipfs.io/ipfs/QmapYFFA7WqSKQdeSZofrg9W7KCna9poAAFCiDqoqT8KM9/) does not load properly because URLs of static files are absolute. To work correctly when opened on IPFS gateway the site should use relative URLs.

If you're using vue, setting `publicPath: './'` in `vue.config.js` might fix this.

**Comment by MicahZoltu** [comment]
Any chance of this getting fixed?  Either DNSLink should be disabled, or the site should actually work in IPFS.  If you have IPFS Companion installed, or are using Brave browser with experimental IPFS support, the page doesn't load at all right now because DNSLink will result in the page getting redirected to your preferred IPFS gateway, and then the page will proceed to fail to load.

**Comment by bonustrack** [comment]
@xuhcc Thank you, we will get this fixed. I just wonder how do you get the current IPFS hash?

**Comment by xuhcc** [comment]
I'm using [ipfs-companion](https://github.com/ipfs-shipyard/ipfs-companion) browser extension which automatically redirects me to IPFS version if it is available (for example when the domain has [DNSLink](https://dnslink.io) enabled). It seems that DNSLink is currently disabled at https://snapshot.page/.
Or you mean how to get it when you're building for production? You can add the directory which contains the `index.html` file (e.g. `dist/`) to IPFS and IPFS node will return hash of this directory. I'm not familiar with Fleek but it looks like its CI service logs IPFS hash during the build:

```
2020-12-31T11:02:02.768Z: Deployed to IPFS and got the hash:
2020-12-31T11:02:02.768Z: Qmf1T3qxK7jRLDRENPLRSkdYEYfivdQTy4o4UX2LkzVHca
```

(log taken from https://github.com/balancer-labs/snapshot/pull/184/checks?check_run_id=1629989620)

**Comment by ChaituVR** [comment]
@xuhcc I tried opening the latest build on ipfs https://ipfs.io/ipfs/QmVQJnjyaGu8JV2tanC9P73GBqV42U2MCv9Dt5qZC134Ds it seems to be working fine in chrome when the browser extension is installed
and without extension http://bafybeidi6gn2nc7hafpwkxdfc7snszdubayia2e4a3bbyjh4uiicdyu6qy.ipfs.localhost:8080/#/
am I missing some step to reproduce it or issue is something else? 🤔

**Comment by MicahZoltu** [comment]
I don't remember exactly what my problem was before, but I can't seem to find all of the files for bafybeidi6gn2nc7hafpwkxdfc7snszdubayia2e4a3bbyjh4uiicdyu6qy via my local IPFS.  I'll leave it trying for a bit and come back here with more info tomorrow.

**Comment by xuhcc** [comment]
@ChaituVR Maybe your gateway uses [subdomain resolution style](https://ipfs.io/ipns/docs.ipfs.io/concepts/ipfs-gateway/#resolution-style). I think in that case extension transforms URLs like `https://ipfs.io/ipfs/content-id` into something like `https://content-id.ipfs.gateway.tld/` so absolute paths don't cause any issues.

You can try to open https://ipfs.io/ipfs/QmVQJnjyaGu8JV2tanC9P73GBqV42U2MCv9Dt5qZC134Ds without extension to reproduce the problem.

**Comment by ChaituVR** [comment]
@xuhcc oh yeah now i get it... 👍 Issue is when we don't have ipfs companion extension installed..

**Comment by xuhcc** [comment]
Yes, but users who use extension + gateway with "path" resolution style (like myself) are affected too.

**Comment by MicahZoltu** [comment]
I believe the latest version of the IPFS companion will automatically redirect CIDv0-as-path to CIDv1-as-subdomain, so IIUC this problem would be specific to users who use the legacy path and don't have IPFS companion installed or are running an older version of the companion.

I still recommend the fix, but if it is true that it doesn't affect CIDv1-as-subdomain links then at least there is a workaround.

Note: I am unable to load the page with `QmVQJnjyaGu8JV2tanC9P73GBqV42U2MCv9Dt5qZC134Ds` or `bafybeidi6gn2nc7hafpwkxdfc7snszdubayia2e4a3bbyjh4uiicdyu6qy`.  Are we sure someone with all of the files is serving them on the IPFS network?

**Comment by xuhcc** [comment]
>I am unable to load the page with QmVQJnjyaGu8JV2tanC9P73GBqV42U2MCv9Dt5qZC134Ds or bafybeidi6gn2nc7hafpwkxdfc7snszdubayia2e4a3bbyjh4uiicdyu6qy. Are we sure someone with all of the files is serving them on the IPFS network?

Both are accessible from my node (including referenced files).

**Comment by ChaituVR** [comment]
@xuhcc @MicahZoltu please check now
