### ISSUE TITLE
min should apply to votes according to strategy @ snapshot block number

### ISSUE THREAD

**Issue by moodysalem** [balancer-labs/snapshot#110]
### Expected behavior
min should apply to votes according to strategy @ snapshot block number
### Actual behavior
min applies to balanceOf of token of proposal signer address
### Steps to reproduce the behavior
create a proposal from account that has enough votes according to strategies to exceed min
it does not show up

**Comment by bonustrack** [comment]
I'll look on this today, but to begin with, it will use the current block number not the snapshot of the proposal.
