### ISSUE TITLE
Fortmatic wallet bug

### ISSUE THREAD

**Issue by ethedev** [balancer-labs/snapshot#144]
# Fortmatic wallet bug
Page get stuck if we were trying to connect Fortmatic wallet.

**To reproduce:**
- go to the website
- click connect wallet, click Fortmatic
- wait for it to load
- close the website
- reopen the website
- you will get stuck

<details>
  <summary>Error log</summary>

```
fortmatic.ts:16 Error: Fortmatic RPC Error: [-32603] Fortmatic: User denied account access.
    at new t (fortmatic.js:1)
    at e.<anonymous> (fortmatic.js:1)
    at fortmatic.js:1
    at Object.next (fortmatic.js:1)
    at a (fortmatic.js:1)
```
</details>

**Comment by bonustrack** [comment]
@ethedev Can you still reproduce the issue?

**Comment by ethedev** [comment]
yes the reproduction steps are up, additionally this shows each time you open/close the popup:
> vue.runtime.esm.js:1888 TypeError: Cannot read property 'chainId' of undefined
    at web3.ts:89
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.E.forEach.e.<computed> [as throw] (runtime.js:97)
    at n (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:29)

**Comment by bonustrack** [comment]
This was fixed in https://github.com/snapshot-labs/lock/pull/3 if the issue persist please open that issue again

**Comment by ethedev** [comment]
👍🏼
