### ISSUE TITLE
Swap out "MetaMask" logo for generic "Web3" logo on the connector modal

### ISSUE THREAD

**Issue by john-light** [balancer-labs/snapshot#147]
If a voter uses [Frame](https://frame.sh) as their signing interface, they must currently know to select "MetaMask" from the list of connection options:

![Screenshot_2020-10-21 Snapshot](https://user-images.githubusercontent.com/9424721/96809038-1c1dfd80-13e8-11eb-9f76-09ba9b593838.png)

I can think of two solutions to make this more intuitive:
- Add a logo for Frame too, but this option doesn't scale well; it implies that for each Web3 signing tool a new logo should be added to this modal, which could eventually make it cluttered with a ton of logos for users to sift through.    
- Add a generic "Web3" logo and remove the MetaMask logo (Coinbase too?), then users of any signing interface that supports generic Web3 connections can click the Web3 button and not have to sort through a bunch of logos to find their specific signer.

**Comment by bonustrack** [comment]
We've implemented that just now here https://github.com/balancer-labs/snapshot/commit/3582a4540b74b234ee4018104a4ebd8b89a8d2ee#diff-94e01b9bcaf37dddbea5defec6f62b685b2f2362d74b42d01d29fab89a70432b Thanks!
