### ISSUE TITLE
Post length

### ISSUE THREAD

**Issue by milkyklim** [balancer-labs/snapshot#163]
When creating long proposal it gets cut in UI – is there length restriction? Can you add indication to UI?

**Comment by bonustrack** [comment]
@milkyklim Yes there is a length restriction of 10k characters, if you had pasted a text it was probably cut directly on the input before being sent. We've just pushed a change so it's now possible to paste any text size in the input without having it being cut and there is now an indicator of the text length overflow shown on the UI.
 
![image](https://user-images.githubusercontent.com/16245250/99910406-6adcf100-2d20-11eb-99c4-89eab36a2cb1.png)

Sorry for the delay just noticed the issue.

**Comment by bonustrack** [comment]
Closing this issue it's already been fixed.
