### ISSUE TITLE
Report from "Download report" is broken

### ISSUE THREAD

**Issue by john-light** [balancer-labs/snapshot#166]
**Describe the bug**
The CSV that the "Download report" button provides doesn't actually have the vote information expected.

**Expected behavior**
I expect a report with votes, addresses, token amount voted, signatures, etc.

**Screenshots**

Report from: https://gov.aragon.org/#/aragon/proposal/Qmb2ZWCUcbTmTGg1Hfu8b8QNZ6vFhW74n614dEdjuwttku

![vote-report](https://user-images.githubusercontent.com/9424721/99833034-7e753580-2b2f-11eb-8712-a91763e157c3.png)

**Desktop (please complete the following information):**
 - OS: Mint 19.3
 - Browser: Firefox 82.0.2
 - Spreadsheet: Libre Office 6.0.7.3 - Calc

**Comment by samuveth** [comment]
Hi @john-light, I just downloaded the report from the proposal you provided and I can see all the votes.
<img width="1251" alt="Screen Shot 2020-12-31 at 11 44 10 AM" src="https://user-images.githubusercontent.com/51686767/103394866-9cd24600-4b5d-11eb-900a-f760212ab4a6.png">

Maybe it's an issue with the tool that you’re using to open the it? Could you try opening the same file here sheets.google.com.
