### ISSUE TITLE
Wrong Image inside Connect Wallet button when we cancel login

### ISSUE THREAD

**Issue by ChaituVR** [balancer-labs/snapshot#177]
**Describe the bug**
Wrong Image inside Connect Wallet button when we cancel login

**To Reproduce**
1. Go to https://snapshot.page/#/
2. Click on 'Connect Wallet', then select metamask, close it without connecting
4. See an error

**Expected behavior**
should show "Connect wallet"

**Screenshots**
![image](https://user-images.githubusercontent.com/15967809/101785687-0b098700-3b23-11eb-8026-c35b169dda86.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  87.0.4280.88

**Comment by bonustrack** [comment]
@ChaituVR Do you want to fix this?

**Comment by ChaituVR** [comment]
@bonustrack sure I will pick it soon..  also for this issue whenever the user closes login, he won't be able to select another wallet... the loading icon keeps showing up.. until he reloads the page

**Comment by bonustrack** [comment]
This was fixed in https://github.com/snapshot-labs/lock/pull/3 if the issue persist please open that issue again
