### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by justincavery** [balancer-labs/snapshot#197]
**Describe the bug**
When I visit https://snapshot.page through my ISP (BT in the UK) i'm getting an error on every browser

`SSL_ERROR_RX_RECORD_TOO_LONG`

When I run https://www.ssllabs.com/ssltest/analyze.html?d=snapshot.page&latest the site is only scoring B's across the board (not sure if that's something that needs looking into).

I've managed to overcome it by Tethering on my mobile data, but that's not the point.

**Expected behavior**
I expect to be able to visit the snapshot.page through my regular internet connection on just about any browser.

**Screenshots**

![image](https://user-images.githubusercontent.com/204469/104184907-1eeb2600-540c-11eb-9f4c-d1c9002dde5f.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6 (18G7016)
 - Browser: Chrome, Safari, Firefox (all latest versions)

**Comment by samuveth** [comment]
Hi @justincavery as this isn't effecting anyone else so far, and you can access through your Tethering, I would suggest that it's an issue on the side of your ISP.

**Comment by justincavery** [comment]
@samuveth upon further investigation the issue was with the ASUS Mesh routers I'm using, I'll need to go through a white list the snapshot site.

With regards to the B grade the snapshot servers are getting, it looks to be down to the support of TLS 1.0 and 1.1. Is this something that's flagged for change, did you want me to submit another ticket for that to capture it?

**Comment by samuveth** [comment]
@justincavery Yes, that would be great if you could open another issue regarding this. Thanks

**Comment by tynes** [comment]
I have a similar issue when going to this website. It gives me `ERR_SSL_PROTOCOL_ERROR` in chrome and even curl throws an error

```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

No problem when visiting the site when tethered to my phone's wifi
